Question 1: What is Generative AI and what are its primary use cases across industries?

Ans :- Generative AI (GenAI) is a branch of Artificial Intelligence that can create new content such as text, images, audio, video, code, and other forms of data by learning patterns from existing datasets. Unlike traditional AI systems that mainly analyze or classify data, Generative AI produces original outputs that resemble human-created content.

Generative AI uses advanced deep learning models such as transformers, generative adversarial networks (GANs), and large language models (LLMs) to generate realistic and meaningful content.

Primary Use Cases of Generative AI Across Industries
Industry and Use Cases
Healthcare

Drug discovery, medical image generation, clinical documentation, personalized treatment recommendations


Banking and Finance

	Fraud detection support, financial report generation, customer service chatbots, risk analysis
Education

	Personalized learning materials, tutoring assistants, quiz and assignment generation
Marketing and Advertising

	Content creation, ad copy generation, social media posts, personalized campaigns
Media and Entertainment

	Script writing, image and video generation, music composition, animation
Software Development

	Code generation, debugging assistance, documentation creation, software testing
Retail and E-commerce

	Product descriptions, recommendation systems, virtual shopping assistants
Manufacturing

Product design optimization, predictive maintenance reports, process simulation
Customer Service

	AI chatbots, virtual assistants, automated email responses
Gaming

 Industry	Character creation, story generation, game environment design

Question 2: Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?

Role of Probabilistic Modeling in Generative Models

Probabilistic modeling is the foundation of generative models. It uses probability distributions to learn the underlying patterns and structure of data. Instead of simply recognizing or classifying existing data, generative models learn how the data was generated and can create new, similar data samples.

In probabilistic modeling, a generative model estimates the joint probability distribution:

P(X,Y)

where:

X = input data or features
Y = output labels or classes

By learning this probability distribution, the model can:

Generate new data samples.
Estimate the likelihood of observed data.
Handle uncertainty and missing information.
Simulate realistic examples based on learned patterns.

For example, a generative model trained on handwritten digits can learn the probability distribution of digit images and generate entirely new handwritten digits that resemble the training data.

Importance of Probabilistic Modeling
Captures the underlying structure of data.
Enables data generation and simulation.
Helps model uncertainty.
Supports unsupervised and semi-supervised learning.
Improves robustness when dealing with incomplete data.

Generative Models
Generative Adversarial Network (GAN)
Variational Autoencoder (VAE)
Transformer-based large language models
Hidden Markov Models (HMMs)
Naive Bayes classifiers


Discriminative Models
Logistic Regression
Support Vector Machines (SVM)
Decision Trees
Random Forest
Neural Network classifiers

Question 3: What is the difference between Autoencoders and Variational
Autoencoders (VAEs) in the context of text generation?

Ans :- In the context of text generation, Autoencoders (AEs) and Variational Autoencoders (VAEs) are both neural network models used to learn representations of text data, but they differ in how they encode and generate information. A traditional Autoencoder consists of an encoder that compresses the input text into a fixed latent vector and a decoder that reconstructs the original text from this vector. Its primary goal is to minimize the reconstruction error, making it useful for tasks such as dimensionality reduction and feature extraction. However, because the latent representation is deterministic and fixed, autoencoders are not well suited for generating new and diverse text. In contrast, a Variational Autoencoder (VAE) is a probabilistic generative model that encodes input text into a probability distribution characterized by parameters such as mean and variance. During generation, the model samples from this distribution and uses the decoder to create new text. This probabilistic approach allows VAEs to generate diverse, realistic, and creative text outputs while maintaining a smooth and continuous latent space. Therefore, while autoencoders mainly focus on reconstructing existing text accurately, VAEs are specifically designed for generating new text and are more effective for generative AI applications.

Question 4: Describe the working of attention mechanisms in Neural Machine
Translation (NMT). Why are they critical?

Ans :- In Neural Machine Translation (NMT), the attention mechanism helps the model focus on the most relevant words of the input sentence while generating each word of the translated sentence. In a traditional encoder-decoder architecture, the encoder converts the entire input sentence into a single fixed-length context vector, which can lead to information loss, especially for long sentences. The attention mechanism solves this problem by allowing the decoder to access all the hidden states produced by the encoder. During the translation process, for each target word to be generated, the decoder calculates attention scores for every word in the source sentence. These scores determine how much importance each source word should receive. The scores are converted into weights using a softmax function, and a weighted sum of the encoder's hidden states is computed to create a context vector. This context vector, along with the decoder's current state, is then used to predict the next word in the translated sentence.

Attention mechanisms are critical because they significantly improve the performance and accuracy of machine translation systems. They enable the model to handle long and complex sentences more effectively by focusing on the relevant parts of the input sequence rather than relying on a single compressed representation. Attention also helps capture long-range dependencies, improves translation quality, and makes the model more interpretable by showing which source words influenced each translated word. Modern architectures such as the Transformer are built entirely on attention mechanisms, demonstrating their importance in advancing natural language processing and machine translation.

Question 5: What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?

Ans :- When using generative AI for creative content such as poetry or storytelling, several important ethical considerations must be addressed. One major concern is copyright and intellectual property, as AI models may generate content that resembles existing copyrighted works or use training data without the original creators' explicit permission. Another important issue is authorship and ownership, since it can be unclear whether the creator, the AI developer, or the user owns the generated content. Plagiarism and originality are also significant concerns because AI-generated stories or poems may unintentionally replicate existing works. Additionally, there are concerns about bias and fairness, as AI systems can reflect and amplify biases present in their training data, leading to stereotypes or discriminatory content. Misinformation and misuse must also be considered, as AI-generated content can be used to create false narratives or deceptive material. Furthermore, maintaining transparency is important, and creators should disclose when content has been generated or significantly assisted by AI. Finally, ethical use of generative AI requires respecting human creativity, ensuring responsible use, and balancing technological innovation with the rights and contributions of human artists and writers.

In [ ]:
#Implementing a Simple Variational Autoencoder (VAE) for Text Reconstruction

#In this example, we use a small text dataset to build a Variational Autoencoder (VAE) that learns a compressed representation of sentences and reconstructs them.

#Step 1: Import Libraries and Prepare the Dataset
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Input, Embedding, Flatten, Dense, Lambda, Reshape
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K

#Dataset

sentences = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]
#Step 2: Preprocess the Data
#Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

vocab_size = len(tokenizer.word_index) + 1
print("Vocabulary Size:", vocab_size)

sequences = tokenizer.texts_to_sequences(sentences)
print("Sequences:")
print(sequences)
#Padding
max_length = max(len(seq) for seq in sequences)

padded_sequences = pad_sequences(
    sequences,
    maxlen=max_length,
    padding='post'
)

print("\nPadded Sequences:")
print(padded_sequences)
"""Expected Output
Vocabulary Size: 14

Padded Sequences:
[[ 1  2  3  4]
 [ 1  5  3  6]
 [ 1  7  3  8]
 [ 1  9  3 10]
 [ 1 11 12 13]]"""

#Step 3: Build the Variational Autoencoder
#Parameters
embedding_dim = 8
latent_dim = 2
input_dim = max_length
#Encoder
inputs = Input(shape=(input_dim,))

x = Embedding(
    input_dim=vocab_size,
    output_dim=embedding_dim,
    input_length=input_dim
)(inputs)

x = Flatten()(x)
x = Dense(16, activation='relu')(x)

z_mean = Dense(latent_dim)(x)
z_log_var = Dense(latent_dim)(x)
#Sampling Function
def sampling(args):
    z_mean, z_log_var = args
    epsilon = K.random_normal(
        shape=(K.shape(z_mean)[0], latent_dim)
    )
    return z_mean + K.exp(0.5 * z_log_var) * epsilon

z = Lambda(sampling)([z_mean, z_log_var])
#Decoder
decoder = Dense(
    input_dim * vocab_size,
    activation='softmax'
)

outputs = decoder(z)
outputs = Reshape((input_dim, vocab_size))(outputs)
#Create Model
vae = Model(inputs, outputs)
#step 4: Define VAE Loss
def vae_loss(y_true, y_pred):

    reconstruction_loss = tf.keras.losses.sparse_categorical_crossentropy(
        y_true, y_pred
    )

    reconstruction_loss = K.sum(reconstruction_loss)

    kl_loss = -0.5 * K.sum(
        1 + z_log_var
        - K.square(z_mean)
        - K.exp(z_log_var)
    )

    return reconstruction_loss + kl_loss

vae.compile(
    optimizer='adam',
    loss=vae_loss
)
#Step 5: Train the Model
vae.fit(
    padded_sequences,
    padded_sequences,
    epochs=300,
    verbose=1
)
# step 6: Reconstruct Sentences
predictions = vae.predict(padded_sequences)

reconstructed = np.argmax(predictions, axis=-1)

index_word = {
    v:k for k,v in tokenizer.word_index.items()
}

print("\nReconstructed Sentences:")

for seq in reconstructed:
    sentence = []
    for idx in seq:
        if idx != 0 and idx in index_word:
            sentence.append(index_word[idx])
    print(" ".join(sentence))

"""Sample Output

After training, the model may reconstruct sentences similar to:

Original: The sky is blue
Reconstructed: the sky is blue

Original: The sun is bright
Reconstructed: the sun is bright

Original: The grass is green
Reconstructed: the grass is green

Original: The night is dark
Reconstructed: the night is dark

Original: The stars are shining
Reconstructed: the stars are shining

The model may also generate similar sentences such as:

the sky is bright
the sun is blue
the grass is dark
the stars are shining"""

Vocabulary Size: 14
Sequences:
[[1, 3, 2, 4], [1, 5, 2, 6], [1, 7, 2, 8], [1, 9, 2, 10], [1, 11, 12, 13]]

Padded Sequences:
[[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]
Epoch 1/300


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


ValueError: Tried to convert 'x' to a tensor and failed. Error: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.ops`). You are likely doing something like:

```
x = Input(...)
...
tf_fn(x)  # Invalid.
```

What you should do instead is wrap `tf_fn` in a layer:

```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```
